export const authConstants = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGOUT: "LOGOUT",
    AUTHORIZATION:"AUTHORIZATION"
}
export const registerConstants = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_ERROR: "REGISTER_ERROR",

}
export const restaurantConstants = {
    ADD_RESTAURANT_REQUEST: "ADD_RESTAURANT_REQUEST",
    ADD_RESTAURANT_SUCCESS: "ADD_RESTAURANT_SUCCESS",
    ADD_RESTAURANT_ERROR: "ADD_RESTAURANT_ERROR",
}
