export const routes ={
    LOGIN:'/login',
    REGISTER:'/register',
    HOMEPAGE:'/',
    CONFIRM:'/confirm',
    RESTAURANTS:'/restaurants',
    SINGLERESTAURANTMENU:'/restaurant/menu',
    SINGLERESTAURANTRESERVATION:'/restaurant/reservation',
    SINGLERESTAURANTCONTACT:'/restaurant/contact',
    SHOPPINGBASKET:"/shopping_basket",
    DELIVERYANDPAYMENT:'/delivery/payment',
    PROFILE:"/profile",
    MY_ORDERS:"/my_orders",
    ADMIN_PANEL:'/admin',
    RESTAURANT_DASHBOARD: `/admin/dashboard`,
    RESTAURANT_MENU:"/admin/menu",
    RESTAURANT_ORDERS:"/admin/orders",
    RESTAURANT_WORKERS:"/admin/workers",
    RESTAURANT_EDIT:'/admin/edit',
    RESTAURANT_RESERVATION:'/admin/reservations',
}
